import { Router, type IRouter } from "express";
import healthRouter from "./health";
import staffRouter from "./staff";
import areasRouter from "./areas";
import tasksRouter from "./tasks";
import assignmentsRouter from "./assignments";
import issuesRouter from "./issues";
import notificationsRouter from "./notifications";
import messagesRouter from "./messages";
import taskTypesRouter from "./taskTypes";
import dashboardRouter from "./dashboard";
import storageRouter from "./storage";
import locationsRouter from "./locations";
import schedulesRouter from "./schedules";
import sharedPhotosRouter from "./sharedPhotos";
import weeklyReportRouter from "./weeklyReport";
import applicationsRouter from "./applications";
import onboardingRouter from "./onboarding";
import quickbooksRouter from "./quickbooks";
import gateRouter from "./gate";
import { gateMiddleware } from "../middlewares/gate";

const router: IRouter = Router();

router.use("/gate", gateRouter);
router.use(gateMiddleware);
router.use(healthRouter);
router.use(dashboardRouter);
router.use("/staff", staffRouter);
router.use("/areas", areasRouter);
router.use("/tasks", tasksRouter);
router.use("/assignments", assignmentsRouter);
router.use("/issues", issuesRouter);
router.use(notificationsRouter);
router.use(messagesRouter);
router.use(taskTypesRouter);
router.use(storageRouter);
router.use(locationsRouter);
router.use("/schedules", schedulesRouter);
router.use("/shared-photos", sharedPhotosRouter);
router.use("/weekly-report", weeklyReportRouter);
router.use("/applications", applicationsRouter);
router.use("/onboarding", onboardingRouter);
router.use("/quickbooks", quickbooksRouter);

export default router;
