export const AREA_SPECIFIC_TASKS: Record<string, { taskName: string; taskOrder: number }[]> = {
  "Level P1 - East": [
    { taskName: "Clean trash bin #1", taskOrder: 16 },
    { taskName: "Clean trash bin #2", taskOrder: 17 },
    { taskName: "Clean trash bin #3", taskOrder: 18 },
    { taskName: "Clean trash bin #4", taskOrder: 19 },
  ],
  "Level P1 - West": [
    { taskName: "Clean trash bin #1", taskOrder: 16 },
    { taskName: "Clean trash bin #2", taskOrder: 17 },
    { taskName: "Clean trash bin #3", taskOrder: 18 },
    { taskName: "Clean trash bin #4", taskOrder: 19 },
    { taskName: "Clean trash bin #5", taskOrder: 20 },
    { taskName: "Clean trash bin #6", taskOrder: 21 },
    { taskName: "Clean trash bin #7", taskOrder: 22 },
    { taskName: "Clean trash bin #8", taskOrder: 23 },
    { taskName: "Clean trash bin #9", taskOrder: 24 },
    { taskName: "Clean trash bin #10", taskOrder: 25 },
    { taskName: "Clean trash bin #11", taskOrder: 26 },
  ],
  "Level P2 - East": [
    { taskName: "Clean trash bin #1", taskOrder: 16 },
    { taskName: "Clean trash bin #2", taskOrder: 17 },
    { taskName: "Clean trash bin #3", taskOrder: 18 },
    { taskName: "Clean trash bin #4", taskOrder: 19 },
  ],
  "Level P2 - West": [
    { taskName: "Clean trash bin #1", taskOrder: 16 },
    { taskName: "Clean trash bin #2", taskOrder: 17 },
    { taskName: "Clean trash bin #3", taskOrder: 18 },
  ],
  "Level P3 - East": [
    { taskName: "Clean trash bin #1", taskOrder: 16 },
    { taskName: "Clean trash bin #2", taskOrder: 17 },
    { taskName: "Clean trash bin #3", taskOrder: 18 },
  ],
  "Level P3 - West": [
    { taskName: "Clean trash bin #1", taskOrder: 16 },
    { taskName: "Clean trash bin #2", taskOrder: 17 },
    { taskName: "Clean trash bin #3", taskOrder: 18 },
  ],
  "Level P4 - East": [
    { taskName: "Clean trash bin #1", taskOrder: 16 },
  ],
  "Level P4 - West": [
    { taskName: "Clean trash bin #1", taskOrder: 16 },
  ],
  "Level R1 - East": [
    { taskName: "Before Lunch — Line 1 Bin #1", taskOrder: 16 },
    { taskName: "Before Lunch — Line 1 Bin #2", taskOrder: 17 },
    { taskName: "Before Lunch — Line 1 Bin #3", taskOrder: 18 },
    { taskName: "Before Lunch — Line 1 Bin #4", taskOrder: 19 },
    { taskName: "Before Lunch — Line 2 Bin #1", taskOrder: 20 },
    { taskName: "Before Lunch — Line 2 Bin #2", taskOrder: 21 },
    { taskName: "Before Lunch — Line 2 Bin #3", taskOrder: 22 },
    { taskName: "Before Lunch — Line 2 Bin #4", taskOrder: 23 },
    { taskName: "Before Lunch — Line 2 Bin #5", taskOrder: 24 },
    { taskName: "Before Lunch — Line 2 Bin #6", taskOrder: 25 },
    { taskName: "Before Lunch — Line 2 Bin #7", taskOrder: 26 },
    { taskName: "Before Lunch — Line 2 Bin #8", taskOrder: 27 },
    { taskName: "Before Lunch — Line 2 Bin #9", taskOrder: 28 },
    { taskName: "Before Lunch — Line 3 Bin #1", taskOrder: 29 },
    { taskName: "Before Lunch — Line 3 Bin #2", taskOrder: 30 },
    { taskName: "Before Lunch — Line 3 Bin #3", taskOrder: 31 },
    { taskName: "Before Lunch — Line 3 Bin #4", taskOrder: 32 },
    { taskName: "Before Lunch — Line 3 Bin #5", taskOrder: 33 },
    { taskName: "Before Lunch — Line 3 Bin #6", taskOrder: 34 },
    { taskName: "Before Lunch — Elevator Bin #1", taskOrder: 35 },
    { taskName: "Before Lunch — Elevator Bin #2", taskOrder: 36 },
    { taskName: "Before Lunch — Elevator Bin #3", taskOrder: 37 },
    { taskName: "After Lunch — Line 1 Bin #1", taskOrder: 38 },
    { taskName: "After Lunch — Line 1 Bin #2", taskOrder: 39 },
    { taskName: "After Lunch — Line 1 Bin #3", taskOrder: 40 },
    { taskName: "After Lunch — Line 1 Bin #4", taskOrder: 41 },
    { taskName: "After Lunch — Line 2 Bin #1", taskOrder: 42 },
    { taskName: "After Lunch — Line 2 Bin #2", taskOrder: 43 },
    { taskName: "After Lunch — Line 2 Bin #3", taskOrder: 44 },
    { taskName: "After Lunch — Line 2 Bin #4", taskOrder: 45 },
    { taskName: "After Lunch — Line 2 Bin #5", taskOrder: 46 },
    { taskName: "After Lunch — Line 2 Bin #6", taskOrder: 47 },
    { taskName: "After Lunch — Line 2 Bin #7", taskOrder: 48 },
    { taskName: "After Lunch — Line 2 Bin #8", taskOrder: 49 },
    { taskName: "After Lunch — Line 2 Bin #9", taskOrder: 50 },
    { taskName: "After Lunch — Line 3 Bin #1", taskOrder: 51 },
    { taskName: "After Lunch — Line 3 Bin #2", taskOrder: 52 },
    { taskName: "After Lunch — Line 3 Bin #3", taskOrder: 53 },
    { taskName: "After Lunch — Line 3 Bin #4", taskOrder: 54 },
    { taskName: "After Lunch — Line 3 Bin #5", taskOrder: 55 },
    { taskName: "After Lunch — Line 3 Bin #6", taskOrder: 56 },
    { taskName: "After Lunch — Elevator Bin #1", taskOrder: 57 },
    { taskName: "After Lunch — Elevator Bin #2", taskOrder: 58 },
    { taskName: "After Lunch — Elevator Bin #3", taskOrder: 59 },
  ],
  "Level R1 - West": [
    { taskName: "Before Lunch — Bin #1", taskOrder: 16 },
    { taskName: "Before Lunch — Bin #2", taskOrder: 17 },
    { taskName: "Before Lunch — Bin #3", taskOrder: 18 },
    { taskName: "After Lunch — Bin #1", taskOrder: 19 },
    { taskName: "After Lunch — Bin #2", taskOrder: 20 },
    { taskName: "After Lunch — Bin #3", taskOrder: 21 },
  ],
  "Level R2 - East": [
    { taskName: "Clean trash bin #1", taskOrder: 16 },
    { taskName: "Clean trash bin #2", taskOrder: 17 },
    { taskName: "Clean trash bin #3", taskOrder: 18 },
    { taskName: "Clean trash bin #4", taskOrder: 19 },
    { taskName: "Clean trash bin #5", taskOrder: 20 },
    { taskName: "Clean trash bin #6", taskOrder: 21 },
    { taskName: "Clean trash bin #7", taskOrder: 22 },
    { taskName: "Clean trash bin #8", taskOrder: 23 },
    { taskName: "Clean trash bin #9", taskOrder: 24 },
    { taskName: "Clean trash bin #10", taskOrder: 25 },
    { taskName: "Clean trash bin #11", taskOrder: 26 },
    { taskName: "Clean trash bin #12", taskOrder: 27 },
    { taskName: "Clean trash bin #13", taskOrder: 28 },
    { taskName: "Clean trash bin #14", taskOrder: 29 },
    { taskName: "Clean trash bin #15", taskOrder: 30 },
    { taskName: "Clean trash bin #16", taskOrder: 31 },
    { taskName: "Clean trash bin #17", taskOrder: 32 },
    { taskName: "Clean trash bin #18", taskOrder: 33 },
    { taskName: "Clean trash bin #19", taskOrder: 34 },
    { taskName: "Clean trash bin #20", taskOrder: 35 },
    { taskName: "Clean trash bin #21", taskOrder: 36 },
    { taskName: "Clean trash bin #22", taskOrder: 37 },
    { taskName: "Clean trash bin #23", taskOrder: 38 },
    { taskName: "Clean trash bin #24", taskOrder: 39 },
    { taskName: "Clean trash bin #25", taskOrder: 40 },
    { taskName: "Clean trash bin #26", taskOrder: 41 },
    { taskName: "Clean trash bin #27", taskOrder: 42 },
    { taskName: "Clean trash bin #28", taskOrder: 43 },
    { taskName: "Clean trash bin #29", taskOrder: 44 },
    { taskName: "Clean trash bin #30", taskOrder: 45 },
  ],
  "Level R2 - West": [
    { taskName: "Clean trash bin #1", taskOrder: 16 },
    { taskName: "Clean trash bin #2", taskOrder: 17 },
    { taskName: "Clean trash bin #3", taskOrder: 18 },
    { taskName: "Clean trash bin #4", taskOrder: 19 },
    { taskName: "Clean trash bin #5", taskOrder: 20 },
    { taskName: "Clean trash bin #6", taskOrder: 21 },
    { taskName: "Clean trash bin #7", taskOrder: 22 },
    { taskName: "Clean trash bin #8", taskOrder: 23 },
    { taskName: "Clean trash bin #9", taskOrder: 24 },
    { taskName: "Clean trash bin #10", taskOrder: 25 },
    { taskName: "Clean trash bin #11", taskOrder: 26 },
    { taskName: "Clean trash bin #12", taskOrder: 27 },
    { taskName: "Clean trash bin #13", taskOrder: 28 },
    { taskName: "Clean trash bin #14", taskOrder: 29 },
    { taskName: "Clean trash bin #15", taskOrder: 30 },
    { taskName: "Clean trash bin #16", taskOrder: 31 },
    { taskName: "Clean trash bin #17", taskOrder: 32 },
    { taskName: "Clean trash bin #18", taskOrder: 33 },
    { taskName: "Clean trash bin #19", taskOrder: 34 },
    { taskName: "Clean trash bin #20", taskOrder: 35 },
    { taskName: "Clean trash bin #21", taskOrder: 36 },
    { taskName: "Clean trash bin #22", taskOrder: 37 },
    { taskName: "Clean trash bin #23", taskOrder: 38 },
    { taskName: "Clean trash bin #24", taskOrder: 39 },
    { taskName: "Clean trash bin #25", taskOrder: 40 },
    { taskName: "Clean trash bin #26", taskOrder: 41 },
    { taskName: "Clean trash bin #27", taskOrder: 42 },
    { taskName: "Clean trash bin #28", taskOrder: 43 },
    { taskName: "Clean trash bin #29", taskOrder: 44 },
    { taskName: "Clean trash bin #30", taskOrder: 45 },
    { taskName: "Clean trash bin #31", taskOrder: 46 },
    { taskName: "Clean trash bin #32", taskOrder: 47 },
    { taskName: "Clean trash bin #33", taskOrder: 48 },
    { taskName: "Clean trash bin #34", taskOrder: 49 },
    { taskName: "Clean trash bin #35", taskOrder: 50 },
    { taskName: "Clean trash bin #36", taskOrder: 51 },
    { taskName: "Clean trash bin #37", taskOrder: 52 },
    { taskName: "Clean trash bin #38", taskOrder: 53 },
    { taskName: "Clean trash bin #39", taskOrder: 54 },
    { taskName: "Clean trash bin #40", taskOrder: 55 },
    { taskName: "Clean trash bin #41", taskOrder: 56 },
    { taskName: "Clean trash bin #42", taskOrder: 57 },
    { taskName: "Clean trash bin #43", taskOrder: 58 },
    { taskName: "Clean trash bin #44", taskOrder: 59 },
    { taskName: "Clean trash bin #45", taskOrder: 60 },
    { taskName: "Clean trash bin #46", taskOrder: 61 },
    { taskName: "Clean trash bin #47", taskOrder: 62 },
    { taskName: "Clean trash bin #48", taskOrder: 63 },
    { taskName: "Clean trash bin #49", taskOrder: 64 },
    { taskName: "Clean trash bin #50", taskOrder: 65 },
    { taskName: "Clean trash bin #51", taskOrder: 66 },
  ],
};
