from pathlib import Path
import json, textwrap, hashlib, zipfile, shutil
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor, white
from reportlab.lib.utils import ImageReader
from pypdf import PdfReader
SOURCE_ROOT=Path(__file__).resolve().parent
ROOT=SOURCE_ROOT.parent.parent/'generated'/'onboarding-forms'/'pdf'; ROOT.mkdir(parents=True,exist_ok=True)
LOGO=str(SOURCE_ROOT/'marvol-logo.jpeg')
GREEN=HexColor('#086449'); GRAY=HexColor('#475569'); INK=HexColor('#152536')
forms=[]
def form(id,title,owner,sections,notice='',restricted=False):
 forms.append(dict(id=id,title=title,owner=owner,sections=sections,notice=notice,restricted=restricted))
def S(title,fields=(),text=''): return dict(title=title,fields=list(fields),text=text)
ID=['Employee full name','Employee ID / hire reference','Role / work location','Prepared by / date']
SIGN=['Employee typed signature / date','Reviewer typed signature / date']
STATUS='Record Not started, In progress, Completed, Needs correction, or Not applicable with reason. Evidence references must point to authorized private records; do not enter identity numbers.'
form('onboarding-cover','Employee Onboarding Cover Sheet','HR / Operations',[S('Employee and owners',ID+['Proposed start date / actual first paid day','Supervisor / training buddy','HR owner / payroll owner','Authorized airport sponsor']),S('Scope and support',['Training language / accessibility arrangement','Authorized areas / approved equipment','Overall status / next due item','Next review date / responsible contact','Employee / supervisor confirmation'])], 'Use Preparing, In training, Needs support, Awaiting access, Ready, or Closed. This cover sheet does not grant work or airport access.')
admin=['Accepted offer / exact version confirmed','Duplicate employee record check','Employee I-9 Section 1 received','Employer I-9 examination / Section 2 complete','W-4 received / payroll enrollment route ready','E-Verify deadline and authorized owner assigned','Emergency contact privately recorded','Applicable airport access requirements verified','Uniform / task-specific PPE / equipment issued','Own account / recovery route tested','Language / accessibility needs arranged','Orientation / buddy shifts scheduled']
form('administrative-checklist','Administrative Onboarding Checklist','HR / Administrator',[S('Record',ID),S('Checklist - status, owner, due date, evidence',admin),S('Review',['Outstanding actions / owners / due dates','HR reviewer signature / date','Operations review reference'])],STATUS)
form('conditional-offer','Conditional Offer of Employment','HR / Hiring approver',[S('Candidate and offer',['Candidate full name / contact details','Offer reference / version / issue date','Job title / reporting supervisor','Primary work location / proposed first day','Reporting time / location']),S('Approved terms',['Employment arrangement','Hourly rate or salary / currency / classification','Schedule expectations','Verified payroll frequency','Benefits / leave policy reference','Paid orientation / training arrangements','Role-specific duties','Actual approved offer conditions','Enclosed job description / policy attachments','Acceptance deadline / time zone / HR recipient']),S('Offer statement',text='Marvol Enterprises LLC offers the candidate the position and terms recorded above, subject only to the approved conditions listed. Airport clearance is determined by the airport authority. Restricted-area work requires the applicable authorization. HR will confirm first-day arrangements and any approved assignment limitations. The candidate may ask questions before acceptance. No guaranteed hours, benefits or additional employment clauses are created by this blank template.'),S('Approval',['Approved terms verified by / date','Authorized signatory name / title','Authorized signatory signature / date'])], 'TEMPLATE - HR must complete all terms and conditions before issuing. This blank document is not an offer to any person.')
form('offer-acceptance','Candidate Offer Acceptance','Candidate / HR',[S('Offer being accepted',['Candidate full name / contact details','Job title / accepted offer date','Exact offer reference / version','Agreed pay / employment arrangement','Proposed start date']),S('Acceptance',text='I accept the identified Marvol Enterprises LLC offer on the terms in that offer and its listed attachments. I had an opportunity to review it and ask questions. I will complete the agreed preboarding steps and attend orientation. This acceptance does not state that I hold an airport badge or have completed required training. Please confirm receipt and first-day reporting instructions.'),S('Candidate signature',['Candidate signature / date','Offer attachments accepted / amendment references']),S('HR receipt',['Received by / server record reference / date'])], 'Attach the exact issued offer. Signing this acceptance does not change its terms or grant airport access.')
form('acceptance-receipt','HR Acceptance Receipt and Welcome','HR',[S('Receipt',['Employee full name','Accepted offer reference / version','Job title / acceptance received date','HR name / contact']),S('Welcome arrangements',['Proposed start / specific outstanding conditions','Supervisor name / contact','Reporting location / time - subject to confirmation','Next document / orientation / badging actions and due dates','Approved private document channel','Paid training time process','Verified items to bring','Language / accessibility contact']),S('Receipt statement',text='Marvol confirms receipt of the identified acceptance. HR will confirm final start arrangements separately. Required orientation and training will be scheduled and recorded through the approved paid-time process.'),S('HR confirmation',['HR signature / date'])], 'Receipt only; this is not a statement that every start condition has been satisfied.')
form('start-confirmation','Final Start-Confirmation Letter','Authorized HR signatory',[S('Reference',['Employee full name / job title','Accepted offer date / reference / version','Accepted amendments / references','Verified status of applicable offer conditions']),S('Confirmed arrangements',['First day / reporting time','Reporting location / supervisor contact','Authorized work area / access scope','Approved assignment limitations while badge pending','Paid orientation / training process','Items to bring / HR contact']),S('Confirmation',text='Marvol Enterprises LLC confirms the start arrangements recorded above. Compensation and other agreed terms remain those in the accepted offer and accepted amendments. Complete Employment > Onboarding training, employee acknowledgments and practical assessment. Independent assignment requires the separate supervisor and Operations Manager release. This letter does not grant airport clearance or assert that a pending official case is approved.'),S('Authorization',['Authorized signatory name / title','Signature / date','Employee receipt / date'])], 'Do not enter identity numbers, sensitive E-Verify case details or background-check contents. Use the official case process for pending cases.')
form('offer-tracking','Offer Approval and Tracking Record','HR',[S('Candidate',ID),S('Lifecycle',['Hiring approver / approved terms / approval date','Issued offer reference / version / date','Acceptance deadline / delivery evidence','Exact version accepted / signer / date','Outstanding condition / authorized owner / due date','Verified resolution reference','HR receipt / start confirmation references','Amendment / reason / approver / new acceptance','Outcome: Accepted / Declined / Expired / Withdrawn','Outcome date / authorized note','HR signature / date'])], 'Retain prior offer versions and amendments. No automatic employment decision is made by this tracking form.',True)
form('emergency-contact','Employee Emergency Contact Information','Employee / HR',[S('Employee',ID[:3]),S('Primary contact',['Full name / relationship','Primary phone / alternate phone','Preferred language / contact instructions']),S('Alternate contact',['Full name / relationship','Primary phone / alternate phone']),S('Confirmation',SIGN)],'Completed contact details are private HR records. Provide only information needed to contact someone in an emergency.')
form('payroll-setup','Payroll Setup and Training-Time Checklist','HR / Payroll',[S('Employee and payroll',ID+['Accepted offer compensation reference','Payroll frequency / first payroll date','W-4 version received / receipt date','Approved payroll enrollment channel']),S('Setup',['Direct-deposit enrollment status / private provider reference','Payroll identity match verified by / date','Paid orientation and training recording route','Actual first paid day / training time evidence','Missing time / correction reference / approver','Outstanding payroll action / owner / due date','Payroll reviewer signature / date'])], 'Do not enter full bank account, routing or Social Security numbers here. Use the approved payroll provider. W-4 receipt is separate from E-Verify.')
form('language-accessibility','Training Language and Accessibility Plan','Employee / HR / Trainer',[S('Employee',ID),S('Arrangement',['Preferred training language: English / Spanish / Haitian Creole / other','Requested instruction / communication format','Interpreter or accessible alternative / responsible contact','Training material version / arrangement dates','Employee questions / agreed support','Review date / outcome']),S('Confirmation',SIGN)],'Describe the training arrangement, not a diagnosis or unnecessary medical details. Preserve access to the same required instruction and assessments.')
form('uniform-equipment-issue','Uniform, PPE and Equipment Issue Record','Supervisor',[S('Employee',ID),S('Issue checklist',['Black pants / yellow reflective shirt / appropriate footwear','Company ID / separate airport badge status','Issued task-specific PPE / hazard assessment reference','Equipment identifier / condition / authorized scope','Quantity / issue date / issuer','Product-specific instruction and inspection complete','Employee demonstration / restrictions','Replacement / return action and due date']),S('Receipt',SIGN)],'Select PPE for the actual product and task. Issue of equipment does not itself authorize operation.')
form('site-orientation','Site Orientation and GOAA Clock-In Checklist','Supervisor',[S('Employee and site',ID),S('Local safety information',['Actual emergency number / contact','Assembly point / exits / evacuation route','Incident reporting route / immediate-call contact','SDS location / approved product list','Storage / supply locations / approved equipment','Authorized areas / airport access boundaries','Pedestrian / vehicle controls / site hazards']),S('Employee workflow',text='At the start of the shift: Sign/Clock in to the GOAA portal on the ground floor using the employee\'s own authorized credentials. Record actual time in Marvol through the approved process. Follow the assigned cleaning route, report hazards promptly, complete only work actually done, perform final inspection and hand over unfinished work. If either timekeeping system fails, notify the supervisor and use the approved actual-time fallback.'),S('Demonstration',['GOAA ground-floor sign/clock-in demonstrated / date','Own Marvol sign-in / time / breaks / correction demonstrated','Assigned tasks / photos / incident / supplies demonstrated','Final inspection / handover demonstrated','Questions / supervisor responses']),S('Confirmation',SIGN)],'GOAA site timekeeping and Marvol time records must reflect actual work. Do not share accounts or assume the app is the only emergency channel.')
form('orientation-acknowledgment','Company Orientation and Policy Acknowledgment','Employee / Supervisor',[S('Employee',ID),S('Topics reviewed',['Reporting line / attendance / shift expectations','Respectful conduct / harassment concern reporting','Confidentiality / responsible task-photo use','Timekeeping / breaks / paid mandatory training','Customer and passenger interactions','Safety stop-work / reporting / help contacts','Policy documents and exact versions supplied','Employee questions / responses']),S('Acknowledgment',text='I received the identified orientation and policies in a format I understand, had the opportunity to ask questions, and know how to request help and report concerns. My acknowledgment is a record of receipt and instruction, not a waiver of rights or a substitute for observed competence.'),S('Signatures',SIGN)])
form('training-attendance','Paid Orientation and Training Attendance','Trainer / Payroll',[S('Employee',ID),S('Session',['Training module / version','Trainer / language / delivery format','Actual start / end / breaks / total paid minutes','Attendance evidence / time record reference','Topics and products / equipment covered','Questions / responses / accessible alternative','Time correction / approver / reference']),S('Verification',SIGN)],'Record actual required training time through the approved paid-time process. Do not direct staff to complete mandatory training off the clock.')
form('video-attestation','Training Video Employee Attestation','Employee',[S('Training identity',['Employee full name / ID','Training title / training ID / version','Video identifier or hash / language','Full viewing completion time / evidence reference','Knowledge-check result / correction reference']),S('Separate employee confirmations',['I watched the full identified training video: Yes / No','I understand the training and know how to ask for help: Yes / No']),S('Attestation',text='I confirm that I watched the identified training in a language or accessible format I understand. I had an opportunity to ask questions. I understand the procedures covered, know when to stop and request help, and will follow approved site instructions. This records my attestation; my supervisor separately verifies practical competence.'),S('Signature',['Employee full-name signature / date','Approved alternative / HR reviewer / reference','Supervisor review / date'])], 'Use the signed-in employee attestation in Employment > Onboarding as the authoritative app record. This paper/alternative form does not bypass watch progress, identity, quiz or version controls. Never sign for another employee.')
questions=['What do you do before starting to clean an area?','What must you do before using a cleaning chemical?','What is the correct spill-response order?','What do you do with broken glass, sharps or unknown hazardous material?','Can you enter any airport area if a coworker opens the door?','What must be done when emptying a trashcan?','Which surfaces are covered in elevator cleaning?','When can you mark a task complete?','What if the time clock or GPS does not work?','What do you do when a hazard remains at the end of a shift?']
critical={1,2,3,4,5,10}
answers=['Inspect the area, identify hazards and confirm it is safe to proceed.','Check approved product instructions, label and required PPE; know SDS access; never mix products.','Secure the area, place warning signs, use the approved method, inspect before reopening.','Stop direct handling, secure/report the concern and follow the trained site procedure.','No. The employee needs actual authorized access; any escort must follow airport rules.','Empty appropriately, replace the liner and leave the area clean.','Doors, buttons, glass and floor within authorized cleaning scope.','Only after doing the work and providing required evidence.','Notify the supervisor, use the approved actual-time fallback and request an audited correction.','Secure/report the hazard, document unfinished work and hand it over to the supervisor.']
form('knowledge-check','Onboarding Knowledge Check','Employee / Assessor',[S('Attempt',ID+['Training version / attempt date / assessor','Language / accessible format'])]+[S(f'Question {i}'+(' - CRITICAL' if i in critical else ''),['Employee response','Assessor result: Pass / Retrain / comments'],q) for i,q in enumerate(questions,1)]+[S('Result',['Correct answers / total / critical-item results','Corrections taught / reassessment date','Assessor signature / date','Employee acknowledgment / date'])], 'A critical-item failure requires retraining and reassessment for that task. Do not automatically make an employment decision from a score.')
form('knowledge-check-guide','Knowledge Check Assessor Guide','Supervisor / Trainer',[S(f'{i}. '+q,[],a+(' CRITICAL ITEM.' if i in critical else '')) for i,(q,a) in enumerate(zip(questions,answers),1)]+[S('Assessment record',['Assessor name / training version / date','Approved passing standard / critical-item gate','Correction / reassessment reference'])], 'ASSESSOR COPY. Accept equivalent safe responses in a language the employee understands. Critical items must be corrected and reassessed; the guide alone is not employee evidence.',True)
points=['Correct uniform, ID and task-specific PPE','Inspect assigned area before work','Recognize and communicate hazards','Control pedestrian / vehicle exposure','Correct chemical instructions, labeling and SDS knowledge','Inspect equipment / operate only within authorization','Safely remove trash and replace liners','Sweep walkways / curbs without exposing others','Clean specified corners and drains','Approved reach / tools for cobweb work','Clean elevator surfaces safely within scope','Isolate spill / warning signs / check before reopening','Record actual work time and applicable breaks','Accurate completed tasks / photos / reported issues','Final inspection / stock request / handover']
form('practical-assessment','Practical Cleaning Competence Assessment','Supervisor',[S('Exercise',ID+['Assessor / date / site / training version'])]+[S(f'{i}. {p}',['Pass / Retrain / Not applicable with reason','Observed evidence / correction']) for i,p in enumerate(points,1)]+[S('Outcome',['Critical safety concerns / affected tasks blocked','Retraining / reassessment date and result','Supervisor recommendation / signature / date','Employee feedback / acknowledgment'])], 'All applicable points must pass after corrections before recommending independent work. Unsafe chemicals, uncontrolled spills, unauthorized access, unsafe equipment or falsified records block the affected scope.')
form('buddy-shift','Supervised Buddy Shift Record','Buddy / Supervisor',[S('Employee and route',ID+['Buddy / supervisor / assigned scope'])]+[S(f'Supervised shift {i}',['Date / actual hours / route','Demonstration and employee practice observed','Strengths / questions / coaching','Safety issues / restrictions / unfinished tasks','Further supervision needed / next action','Supervisor signature / date']) for i in range(1,4)], 'Demonstrate, observe, then step back as appropriate. Extend supervision when needed; the buddy cannot waive release requirements.')
form('independent-work-release','Independent-Work Readiness and Release','Supervisor / Operations Manager',[S('Employee and scope',ID+['Authorized areas / equipment / tasks']),S('Required gates',['Administrative status / HR verifier / date / reference','Airport clearance / sponsor verifier / expiry / scope','Required training / version / employee attestations','Knowledge check / critical-item outcome','Practical assessment / applicable points passed','Buddy shifts / corrections complete','Remaining restrictions / supervised tasks']),S('Separate approval',['Supervisor recommendation / signature / timestamp','Operations Manager decision / signature / timestamp','Reason / authorized scope / restrictions','Employee notified / first independent shift','Day 7 review date / responsible contact'])], 'Employees cannot approve their own readiness. Ready applies only to the recorded scope; pending requirements do not grant restricted access or authorize unsafe tasks.',True)
for day in (7,30,60,90):
 form(f'day-{day}-review',f'Day {day} Onboarding Follow-Up Review','Supervisor / Employee',[S('Review',ID+['Actual first paid day / scheduled review / actual review date','Reviewer / authorized scope']),S('Observations',['Safety habits / critical concerns','Cleaning quality / inspection evidence','Attendance discussion / time and task record accuracy','App / supply / passenger interaction observations','Employee feedback / unanswered questions','Action / owner / due date / follow-up outcome']),S('Decision',['Continue scope / narrow scope pending retraining / extend onboarding','Reason / support and targeted training','Next review / responsible owner','Reviewer signature / date','Employee comments / signature / date'])], 'Review dates do not create automatic probation, discipline or employment outcomes. Critical safety concerns require correction regardless of total quality score.')
form('exception-correction','Onboarding Exception, Escalation and Retraining','HR / Supervisor / Operations',[S('Record',ID+['Affected item / training version / date']),S('Action',['Issue and immediate safe action','Assigned owner / due date / escalation contact','Approved supervised alternative / restrictions','Employee notified / language or accessibility support','Correction taught / trainer / date','Reassessment evidence / result / date','Resolution / verifier / date','Superseding record reference - retain original']),S('Approval',['Responsible manager signature / date','Employee acknowledgment / date'])], 'Immediate danger uses the site emergency route. This record cannot waive an applicable requirement or overwrite earlier signatures.',True)
form('badging-checklist','Airport Badging Coordination Checklist','Airport-authorized sponsor',[S('Employee and sponsor',ID+['Authorized signatory / contact','Minimum required access scope / not-required reason']),S('Milestones - owner, date, status, evidence',['Official application and instructions verified','Employee privately given document instructions','Official application prepared / signatory sign date','Application entered in official AS portal','Appointment date / location / instructions','Official fingerprinting and airport-review status','Required airport courses complete / evidence','Additional role-specific authorization verified','Badge issued / verified scope / expiry','Badge-rules orientation complete','Manager work-access release reference','Renewal reminders / responsible owner','Return / deactivation evidence when applicable']),S('Verification',['Sponsor signature / date','HR coordination / date'])], 'Marvol coordination form only. Obtain the official GOAA application through the authorized signatory; copies are not accepted. Verify current rules and the five-business-day application validity after signatory signature. Do not store investigation details here.',True)
form('badge-rules-acknowledgment','Airport Badge Rules Employee Acknowledgment','Employee / Sponsor',[S('Employee and authorized scope',ID+['Verified badge type / authorized work area','Sponsor / official training reference']),S('Rules understood',['Approved access areas / badge display and protection','No credential sharing / tailgating / unauthorized entry','Official escort rules if authorized','Immediate lost / stolen / damaged badge reporting route','Blocked reader / disputed access contact - no bypass','Renewal and return obligations']),S('Acknowledgment',text='I understand the recorded badge rules and authorized scope, know the reporting contact and will not share credentials or enter an area without authorization. This company acknowledgment does not replace official airport training, approval or forms.'),S('Signatures',SIGN)])
form('badge-control','Badge Issue, Renewal, Loss and Return Control','Authorized sponsor / HR',[S('Private record',ID+['Badge identifier / type / authorized scope','Official issue / expiry / evidence reference']),S('Lifecycle',['Current official status / verification source / date','Required official training / scope-specific authorization','Renewal due / appointment / reminder owners','Lost / stolen / damaged report / official action reference','Approved assignment limitations while unavailable','Suspension / transfer / separation notification reference','Actual return date / recipient / airport confirmation','Deactivation / close-out confirmation','Unresolved return action / owner / due date']),S('Verification',['Sponsor signature / date','HR review / date'])], 'Do not mark a badge returned solely because employment became inactive. Never extend official validity in this form or record background-check contents.',True)
form('i9-everify-tracker','Employment Verification and E-Verify Control Record','Authorized HR verifier',[S('Employee and timing',ID+['Accepted offer reference / acceptance date','Actual first employment day','Employee I-9 Section 1 receipt / version','Employer Section 2 due / completed / authorized verifier']),S('Official process',['Official I-9 private storage reference','E-Verify authorized user / case-creation due date','Case created date / restricted case reference','Official status / next required action / deadline','Official employee notice / response evidence','Permitted receipt or pending-SSN exception / HR reference','Official resolution / close date / reviewer','W-4 receipt / payroll follow-up - separate status']),S('Verification',['Authorized HR signature / date','Audited correction / superseding reference'])], 'TRACKER ONLY; use official I-9 and E-Verify procedures. I-9 follows offer acceptance. W-4 is a payroll form, not an E-Verify input. A tentative mismatch must follow official notices, rights and deadlines; do not auto-suspend or reject. Keep case and identity details restricted.',True)
modules=['Company expectations','Airport security and access','Uniform / personal readiness / PPE','Hazard recognition','Product-specific chemicals / SDS','Trash and hazardous waste escalation','Sweeping / corners / drains','Cobweb removal / safe reach','Elevator cleaning / permitted scope','Spill response','Equipment / ergonomics / inspection','Own app sign-in / timekeeping','Tasks / photos / unfinished work','Incident / supply reporting','Final inspection / handover']
form('training-matrix','Required Training Module Completion Matrix','Trainer / Supervisor',[S('Employee',ID+['Trainer / language / program version'])]+[S(f'{i}. {m}',['Version / taught date / actual paid minutes','Knowledge / practical evidence / status','Correction / authorized trainer initials']) for i,m in enumerate(modules,1)]+[S('Review',['Outstanding required modules / owner / due date','Supervisor signature / date','Independent-work release reference'])], 'Separate specialized training is required when applicable. The general video does not authorize respirators, powered machinery, bloodborne-pathogen exposure work or other specialized tasks.')
assert len(forms)==30,len(forms)
class Writer:
 def __init__(self,path,title,id,owner,notice):
  self.c=canvas.Canvas(str(path),pagesize=(612,792));self.c.setTitle(title);self.title=title;self.id=id;self.owner=owner;self.notice=notice;self.page=0;self.n=0;self.y=0;self.pages=[];self.new()
 def footer(self):
  self.c.setFont('Helvetica',7);self.c.setFillColor(GRAY);self.c.drawString(42,30,f'Marvol | {self.id} | v1.0 | 2026-10-08');self.c.drawRightString(570,30,f'Page {self.page}')
 def new(self):
  if self.page:self.footer();self.c.showPage()
  self.page+=1;c=self.c;c.setFillColor(GREEN);c.rect(0,713,612,79,fill=1,stroke=0)
  c.setFillColor(white);c.setFont('Helvetica-Bold',14);c.drawString(42,764,'MARVOL ENTERPRISES LLC');c.setFont('Helvetica',8);c.drawString(42,748,'255 S Orange Ave, Suite 104 | Orlando, FL 32801')
  c.drawString(42,734,'Employee onboarding | '+self.owner)
  c.drawImage(LOGO,518,722,54,62,preserveAspectRatio=True,anchor='c',mask='auto')
  c.setFillColor(INK);c.setFont('Helvetica-Bold',16);self.y=689
  for line in textwrap.wrap(self.title,52):c.drawString(42,self.y,line);self.y-=19
  self.y-=8
  if self.page==1 and self.notice:self.text(self.notice,8,100)
 def need(self,h):
  if self.y-h<53:self.new()
 def text(self,text,size=9,width=94):
  for raw in text.split('\n'):
   lines=textwrap.wrap(raw,width) or ['']
   for line in lines:self.need(size+5);self.c.setFillColor(GRAY);self.c.setFont('Helvetica',size);self.c.drawString(42,self.y,line);self.y-=size+5
  self.y-=5
 def section(self,title):
  self.need(45);self.c.setFillColor(GREEN);self.c.setFont('Helvetica-Bold',10)
  for line in textwrap.wrap(title,82):self.c.drawString(42,self.y,line);self.y-=14
  self.c.setStrokeColor(HexColor('#a7d4c0'));self.c.line(42,self.y+5,570,self.y+5);self.y-=6
 def field(self,label):
  lines=textwrap.wrap(label,94);h=14*len(lines)+28;self.need(h+8)
  self.c.setFillColor(INK);self.c.setFont('Helvetica',8)
  for line in lines:self.c.drawString(42,self.y,line);self.y-=12
  self.n+=1;self.c.acroForm.textfield(name=f'{self.id}_{self.n:03}',tooltip=label,x=42,y=self.y-22,width=528,height=23,fontSize=9,borderColor=HexColor('#bdcbd4'),fillColor=HexColor('#f8fafc'),textColor=INK,borderWidth=.6,forceBorder=True,maxlen=2000)
  self.y-=35
 def end(self):self.footer();self.c.save()
manifest=[]
for f in forms:
 filename=f['id']+'.pdf';w=Writer(ROOT/filename,f['title'],f['id'],f['owner'],f['notice'])
 for s in f['sections']:
  w.section(s['title'])
  if s['text']:w.text(s['text'])
  for x in s['fields']:w.field(x)
 w.end();r=PdfReader(ROOT/filename);fields=r.get_fields() or {};assert len(fields)==w.n
 for page in r.pages:
  for a in page.get('/Annots',[]):
   obj=a.get_object();assert obj.get('/Subtype')=='/Widget';assert obj.get('/AP',{}).get('/N') is not None
 manifest.append({k:f[k] for k in ('id','title','owner','notice','restricted')}|dict(filename=filename,version='1.0',pages=len(r.pages),fieldCount=w.n,sha256=hashlib.sha256((ROOT/filename).read_bytes()).hexdigest()))
w=Writer(ROOT/'Marvol_Onboarding_Forms_Index.pdf','Onboarding Forms Packet - Index','forms-index','HR / Operations','30 company templates mapped to the adopted onboarding protocol. Complete and sign actual records through the app or approved private HR process. Blank forms do not create employment terms or authorize access.')
w.section('Official documents and sequence');w.text('Application -> conditional offer and acceptance -> employee I-9 + W-4 -> employer I-9 review -> E-Verify -> final start confirmation. Preserve statutory deadlines and official employee rights. Use the unchanged official I-9, current W-4 and airport-issued badging applications; the company trackers are not substitutes.')
w.text('Official sources: www.uscis.gov/i-9 | www.irs.gov/forms-pubs/about-form-w-4 | web.goaa.aero/airport-business/access-control/')
for i,f in enumerate(manifest,1):w.section(f'{i:02}. {f["title"]}');w.text(f'Owner: {f["owner"]} | {f["pages"]} pages | {f["fieldCount"]} fillable fields. '+('Admin template access. ' if f['restricted'] else '')+'Completed record: private admin access.',8,105)
w.end();(ROOT/'manifest.json').write_text(json.dumps({'company':'Marvol Enterprises LLC','protocolVersion':'1.0','packetVersion':'1.0','created':'2026-10-08','forms':manifest},indent=2))
shutil.copy2(Path(__file__).resolve(),ROOT/'build_forms.py')
shutil.copy2(SOURCE_ROOT/'marvol-logo.jpeg',ROOT/'marvol-logo.jpeg')
shutil.copy2(SOURCE_ROOT/'generator-requirements.txt',ROOT/'generator-requirements.txt')
with zipfile.ZipFile(ROOT/'Marvol_Onboarding_Forms_Packet.zip','w',zipfile.ZIP_DEFLATED) as z:
  for name in [f['filename'] for f in manifest]+['Marvol_Onboarding_Forms_Index.pdf','manifest.json','build_forms.py','marvol-logo.jpeg','generator-requirements.txt']:
   z.write(ROOT/name,name)
print(json.dumps({'forms':len(manifest),'pdfCount':31,'pages':sum(f['pages'] for f in manifest)+len(PdfReader(ROOT/'Marvol_Onboarding_Forms_Index.pdf').pages),'fields':sum(f['fieldCount'] for f in manifest),'packet':str(ROOT/'Marvol_Onboarding_Forms_Packet.zip')}))
