import {
  pgTable,
  text,
  serial,
  integer,
  boolean,
  timestamp,
  unique,
  index,
  check,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { staffTable } from "./staff";

// participantAId / participantBId are null for group conversations;
// non-null (with the ordered-pair constraint) for 1:1 conversations.
export const conversationsTable = pgTable(
  "conversations",
  {
    id: serial("id").primaryKey(),
    participantAId: integer("participant_a_id").references(() => staffTable.id),
    participantBId: integer("participant_b_id").references(() => staffTable.id),
    isGroup: boolean("is_group").notNull().default(false),
    groupName: text("group_name"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    unique("conversations_participants_unique").on(t.participantAId, t.participantBId),
    check("conversations_participants_ordered", sql`${t.participantAId} < ${t.participantBId}`),
  ]
);

export const messagesTable = pgTable(
  "messages",
  {
    id: serial("id").primaryKey(),
    conversationId: integer("conversation_id").notNull().references(() => conversationsTable.id),
    senderId: integer("sender_id").notNull().references(() => staffTable.id),
    // Generated by the client once per compose/send action. PostgreSQL permits
    // multiple NULLs in this unique key for legacy and inbound-email messages.
    clientRequestId: text("client_request_id"),
    body: text("body").notNull(),
    isRead: boolean("is_read").notNull().default(false),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    unique("messages_sender_client_request_unique").on(
      t.senderId,
      t.clientRequestId,
    ),
  ],
);

export type MessageEmailDeliveryStatus =
  | "pending"
  | "sending"
  | "retrying"
  | "accepted"
  | "disabled"
  | "not_configured"
  | "failed";

// Transactional outbox for supervisor -> inspector email. The row is created
// in the same database transaction as the app message and notifications, then
// claimed by a lease-based worker. Snapshotting the delivery fields means a
// later staff-profile edit cannot silently change an already-queued email.
export const messageEmailOutboxTable = pgTable(
  "message_email_outbox",
  {
    id: serial("id").primaryKey(),
    messageId: integer("message_id")
      .notNull()
      .references(() => messagesTable.id, { onDelete: "cascade" }),
    conversationId: integer("conversation_id").notNull(),
    inspectorId: integer("inspector_id").notNull(),
    supervisorId: integer("supervisor_id").notNull(),
    inspectorEmail: text("inspector_email").notNull(),
    inspectorName: text("inspector_name").notNull(),
    supervisorName: text("supervisor_name").notNull(),
    messageBody: text("message_body").notNull(),
    status: text("status")
      .$type<MessageEmailDeliveryStatus>()
      .notNull()
      .default("pending"),
    attemptCount: integer("attempt_count").notNull().default(0),
    nextAttemptAt: timestamp("next_attempt_at").notNull().defaultNow(),
    lockedAt: timestamp("locked_at"),
    lockToken: text("lock_token"),
    lastError: text("last_error"),
    acceptedAt: timestamp("accepted_at"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    unique("message_email_outbox_message_unique").on(t.messageId),
    index("message_email_outbox_ready_idx").on(t.status, t.nextAttemptAt),
    check(
      "message_email_outbox_status_valid",
      sql`${t.status} IN ('pending', 'sending', 'retrying', 'accepted', 'disabled', 'not_configured', 'failed')`,
    ),
    check(
      "message_email_outbox_attempt_count_valid",
      sql`${t.attemptCount} >= 0`,
    ),
  ],
);

// Per-participant tracking for group conversations (also used to track
// last-read position so unread counts work per user in a group).
export const conversationParticipantsTable = pgTable(
  "conversation_participants",
  {
    id: serial("id").primaryKey(),
    conversationId: integer("conversation_id")
      .notNull()
      .references(() => conversationsTable.id),
    staffId: integer("staff_id")
      .notNull()
      .references(() => staffTable.id),
    lastReadAt: timestamp("last_read_at"),
    joinedAt: timestamp("joined_at").notNull().defaultNow(),
  },
  (t) => [unique("conversation_participants_unique").on(t.conversationId, t.staffId)]
);

// Archiving is a per-user view preference. A row means that participant has
// hidden the conversation; it never removes the conversation or its messages
// for anybody else.
export const conversationArchivesTable = pgTable(
  "conversation_archives",
  {
    conversationId: integer("conversation_id")
      .notNull()
      .references(() => conversationsTable.id, { onDelete: "cascade" }),
    staffId: integer("staff_id")
      .notNull()
      .references(() => staffTable.id, { onDelete: "cascade" }),
    archivedAt: timestamp("archived_at").notNull().defaultNow(),
  },
  (t) => [unique("conversation_archives_unique").on(t.conversationId, t.staffId)],
);

// Durable idempotency record for replies accepted from SendGrid Inbound Parse.
// Provider identifiers are stored as SHA-256-derived values rather than raw
// email headers, which avoids retaining unnecessary address metadata.
export const inboundEmailMessagesTable = pgTable("inbound_email_messages", {
  providerMessageId: text("provider_message_id").primaryKey(),
  conversationId: integer("conversation_id")
    .notNull()
    .references(() => conversationsTable.id, { onDelete: "cascade" }),
  senderId: integer("sender_id")
    .notNull()
    .references(() => staffTable.id),
  messageId: integer("message_id").references(() => messagesTable.id, {
    onDelete: "set null",
  }),
  receivedAt: timestamp("received_at").notNull().defaultNow(),
});

export type Conversation = typeof conversationsTable.$inferSelect;
export type Message = typeof messagesTable.$inferSelect;
export type MessageEmailOutbox = typeof messageEmailOutboxTable.$inferSelect;
export type ConversationParticipant = typeof conversationParticipantsTable.$inferSelect;
export type ConversationArchive = typeof conversationArchivesTable.$inferSelect;
export type InboundEmailMessage = typeof inboundEmailMessagesTable.$inferSelect;
